version: '3'

services:
  app:
    image: lifeni/i-seek-you:latest
    container_name: i-seek-you
    restart: unless-stopped
    ports:
      - '8081:8081' # Signaling Server
      - '8082:8082' # STUN Server
