version: '3'

services:
  signaling:
    image: lifeni/i-seek-you:latest
    container_name: i-seek-you
    restart: unless-stopped
    ports:
      - '8081:8081' # Signaling Server

  turn:
    image: lifeni/i-seek-you:latest
    container_name: i-seek-you
    restart: unless-stopped
    network_mode: 'host'
    # ports:
    #   - '3478:3478/udp' # TURN Server
    #   - '49152-65535:49152-65536/udp' # For exchanging data, may have performance issues
